settings:
  title: 'Digicall - Systems Status'
  url: 'https://status.digicallsa.workers.dev/' # used for Slack messages
  logo: digicall-logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: smartswitch-digicall-co-za # unique identifier
    name: smartswitch.digicall.co.za
    description: 'Digicall SA Smartswitch' # default=empty
    url: 'https://smartswitch.digicall.co.za/services/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: www-digicallgroup-co-za
    name: www.digicallgroup.co.za
    description: 'Digicall SA Website'
    url: 'https://www.digicallgroup.co.za'
    method: GET
    expectStatus: 200

  - id: intranet-digicallgroup-co-za
    name: intranet.digicallgroup.co.za
    description: 'Digicall Group Intranet'
    url: 'https://intranet.digicallgroup.co.za/welcome'
    method: GET
    expectStatus: 200
