settings:
  title: 'Digicall SA - Systems Status'
  url: 'https://status.digicallco.za/' # used for Slack messages
  logo: digicall-logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: smartswitch-digicall-co-za # unique identifier
    name: 'SmartSwitch API Server'
    description: 'smartswitch.digicall.co.za' # default=empty
    url: 'https://smartswitch.digicall.co.za/services/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: www-digicallgroup-co-za
    name: 'Digicall Group Website'
    description: 'www.digicallgroup.co.za'
    url: 'https://www.digicallgroup.co.za'
    method: GET
    expectStatus: 200

  - id: intranet-digicallgroup-co-za
    name: 'Digicall Group Intranet'
    description: 'intranet.digicallgroup.co.za'
    url: 'https://intranet.digicallgroup.co.za/welcome'
    method: GET
    expectStatus: 200

  - id: www-digicall-co-za-dpsweb2
    name: 'DPS Web'
    description: 'www.digicall.co.za/DPSWeb2'
    url: 'https://www.digicall.co.za/DPSWeb2/Home/Logon'
    method: GET
    expectStatus: 200

  - id: www-digicallsouthafrica-co-za
    name: 'DSA Web'
    description: 'www.digicallsouthafrica.co.za'
    url: 'https://www.digicallsouthafrica.co.za/Web/Default.aspx'
    method: GET
    expectStatus: 200
    
  - id: www-digistore-africa
    name: 'eCommerce: digistore.africa'
    description: 'www.digistore.africa'
    url: 'https://www.digistore.africa'
    method: GET
    expectStatus: 200

  - id: www-izinga-com
    name: 'Legal Portal'
    description: 'www.izinga.com'
    url: 'https://www.izinga.com'
    method: GET
    expectStatus: 200
